version: '3'

services:
  front:
    container_name: nuxt
    build: .
    command: yarn dev
    tty: true
    volumes:
      - .:/code
    ports:
      - '3000:3000'
      - '24678:24678'

volumes:
  mysqldata: